name: transcendence
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./web_content:/var/www/html:ro
    networks:
      - transcendence_network
    depends_on:
      - game_service
      - user_service

  game_service:
    build: ./requirements/game_service
    container_name: game_service
    depends_on:
      statistics_db:
        condition: service_healthy
    networks:
      - transcendence_network
    environment:
      - DB_HOST=statistics_db
      - DB_PORT=5432
      - DB_USER=bn_user
      - DB_PASS=bn_pass
      - DB_NAME=game_stats_db

  statistics_db:
    image: postgres:15-alpine
    container_name: statistics_db
    environment:
      POSTGRES_USER: bn_user
      POSTGRES_PASSWORD: bn_pass
      POSTGRES_DB: game_stats_db
    volumes:
      - statistics_db_data:/var/lib/postgresql/data 
    networks:
      - transcendence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bn_user -d game_stats_db"]
      interval: 5s
      timeout: 5s
      retries: 5

# ===== USER SERVICE =====
  user_service:
    build: ./requirements/user_service
    container_name: user_service
    env_file: .env
    depends_on:
      user_db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - transcendence_network
  user_db:
    image: postgres:15-alpine
    container_name: user_db
    env_file: .env
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - transcendence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # --- FRONTEND (REACT) ---
  frontend:
      build:
        context: ./requirements/frontend
        dockerfile: Dockerfile
      container_name: react_frontend
      volumes:
        - ./requirements/frontend:/app
        - /app/node_modules
      networks:
        - transcendence_network
      restart: always
      ports:
        - "5173:5173"
      command: ["npm", "run", "dev", "--", "--host"]

networks:
  transcendence_network:
    driver: bridge

volumes:
  user_db_data:
  statistics_db_data: