name: transcendence
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./web_content:/var/www/html:ro
      - user_media:/var/www/media:ro
    restart: unless-stopped
    networks:
      - transcendence_network
    depends_on:
      - game_service
      - user_service
      - combat_service

  game_service:
    build: ./requirements/game_service
    container_name: game_service
    expose:
      - "8080"
    networks:
      - transcendence_network
    restart: unless-stopped

# ===== USER SERVICE =====
  user_service:
    build: ./requirements/user_service
    container_name: user_service
    env_file: .env
    volumes:
      - ./requirements/user_service:/app
      - user_media:/app/media
    depends_on:
      user_db:
        condition: service_healthy
      user_redis:
        condition: service_started
    restart: unless-stopped
    command: daphne -b 0.0.0.0 -p 8000 user_project.asgi:application
    networks:
      - transcendence_network

  user_db:
    image: postgres:15-alpine
    container_name: user_db
    env_file: .env
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - transcendence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s     # How often to check
      timeout: 5s      # How long to wait for a response
      retries: 5       # How many failures before marking as "unhealthy"
      start_period: 5s # Grace period for the initial boot
      
  user_redis:
    image: redis:alpine
    container_name: user_redis
    networks:
      - transcendence_network
    restart: unless-stopped
    
  statistics_db:
    image: postgres:15-alpine
    container_name: statistics_db
    environment:
      POSTGRES_USER: bn_user
      POSTGRES_PASSWORD: bn_pass
      POSTGRES_DB: game_stats_db
    volumes:
      - statistics_db_data:/var/lib/postgresql/data 
    networks:
      - transcendence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bn_user -d game_stats_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  combat_service:
    build: ./requirements/combat_service
    container_name: combat_service
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./requirements/combat_service:/app
      - /app/node_modules
    depends_on:
      combat_db:
        condition: service_healthy
    networks:
      - transcendence_network
    restart: unless-stopped
    command: ["npm", "run", "start:dev"]

  combat_db:
    image: postgres:15-alpine
    container_name: combat_db
    environment:
      POSTGRES_USER: bn_user
      POSTGRES_PASSWORD: bn_pass
      POSTGRES_DB: combat_db
    volumes:
      - combat_db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - transcendence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bn_user -d combat_db"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s

  # --- FRONTEND (REACT) ---
  frontend:
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - ./requirements/frontend:/app
      - /app/node_modules
    networks:
      - transcendence_network
    restart: always
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

networks:
  transcendence_network:
    driver: bridge

volumes:
  user_db_data:
  user_media:
  statistics_db_data:
  combat_db:
