name: transcendence
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web_content:/var/www/html:ro
    networks:
      - transcendence_network
    depends_on:
      - game_service

  game_service:
    build: ./requirements/game_service
    container_name: game_service
    expose:
      - "8080"
    networks:
      - transcendence_network
    restart: always

networks:
  transcendence_network:
    driver: bridge
